version: "3.9"
services:
  server:
    build: .
    volumes:
    - ./app:/var/www/html
    working_dir: /var/www/html
    ports:
      - 80:80
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  myadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
  node:
    image: node
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
  composer:
    image: composer
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
  redis:
    image: redis
    ports:
    - 6379:6379
